[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
airdrop = "BXVXGEWxVvvDotSk929oeSuBHFhNRGFSjEAdVqhBkGh7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
